[package]
name = "kalman"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
plotly = "0.13.3"
plotters = "0.3.7"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
serde = "1.0.219"
